version: "3.7"
services:
  db:
    image: postgres:15
    container_name: db_app
    env_file:
      - .env-non-dev
  app:
    build:
      context: .
    env_file:
      - .env-non-dev
    container_name: bugtracker_app
    ports:
      - 8000:8000
    depends_on:
      - db
    command: bash -c "alembic upgrade head & gunicorn main:app --worker-class uvicorn.workers.UvicornWorker --bind=0.0.0.0:8000"
