"""Cascade delete

Revision ID: 5db98e40181a
Revises: 
Create Date: 2024-01-07 17:52:52.076445

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5db98e40181a'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('hashed_password', sa.String(length=1024), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_superuser', sa.Boolean(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('tasks',
    sa.Column('number', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('priority', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('header', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('executor', sa.Integer(), nullable=True),
    sa.Column('creator', sa.Integer(), nullable=False),
    sa.Column('time_of_creation', sa.TIMESTAMP(), nullable=False),
    sa.Column('time_of_modification', sa.TIMESTAMP(), nullable=False),
    sa.ForeignKeyConstraint(['creator'], ['users.id'], ondelete='NO ACTION'),
    sa.ForeignKeyConstraint(['executor'], ['users.id'], ondelete='NO ACTION'),
    sa.PrimaryKeyConstraint('number')
    )
    op.create_table('Subtasks',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('main_task', sa.Integer(), nullable=False),
    sa.Column('sub_task', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['main_task'], ['tasks.number'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sub_task'], ['tasks.number'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )

    op.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Subtasks')
    op.drop_table('tasks')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###

